### ISSUE TITLE
InteractionContext timestamp error

### ISSUE THREAD

**Issue by kangyoolee** [dico-api/dico#13]
**Explanation: 설명:**

The timestamp value of the _InteractionContext_ is different from the value of the _general Context_.

InteractionContext의 timestamp 값과 일반 Context 의 값이 다르다.

**How to reproduce a bug: 버그를 구현하는 방법:**

```
@interaction.slash(name="test-interaction",description="test")
async def test_(ctx: InteractionContext):
    await ctx.send(str(ctx.id.timestamp))

@client.command(name="test")
async def test__(ctx):
    await ctx.send(str(ctx.timestamp))
```

Run the following code.
다음 코드를 실행한다.

**Image:**

<img width="339" alt="무제" src="https://user-images.githubusercontent.com/45960943/141995647-a4ee6c72-2829-4892-a533-4169b10cbedc.png">

Top is the interactionContext
Below is the normal Context.

위는 인터랙션 Context
아래는 일반

**Comment by eunwoo1104** [comment]
Fixed on latest commit.
