### ISSUE TITLE
[feature req] using PyEE instead

### ISSUE THREAD

**Issue by ghost** [dico-api/dico#2]
hi eun, so there is pyee - python event emitter, it is easy to use. make class inherit from EventEmitter and then just do self.emit('event', data). and u can do then:
```py
@client.on('event')
async def on_event(data):
    # do something
```
ig it is easier. i can make it myself tho

**Comment by ghost** [comment]
ofc the link https://pyee.readthedocs.io/en/latest/

**Comment by eunwoo1104** [comment]
Event listener is already implemented, no need to switch to anything else.
